### ISSUE TITLE
Weird install error

### ISSUE THREAD

**Issue by SiegfriedEhret** [hraban/cl-markdown#2]
Hi, i'm getting the following error when I try to load cl-markdown from quicklisp.
Do you have any idea about that ?

Welcome to GNU CLISP 2.49 (2010-07-07) http://clisp.cons.org/

Copyright (c) Bruno Haible, Michael Stoll 1992, 1993
Copyright (c) Bruno Haible, Marcus Daniels 1994-1997
Copyright (c) Bruno Haible, Pierpaolo Bernardi, Sam Steingold 1998
Copyright (c) Bruno Haible, Sam Steingold 1999-2000
Copyright (c) Sam Steingold, Bruno Haible 2001-2010

Type :h and hit Enter for context help.

;; Loading file /home/siegfried/.clisprc.lisp ...
;;  Loading file /home/siegfried/quicklisp/setup.lisp ...
;;  Loaded file /home/siegfried/quicklisp/setup.lisp
;; Loaded file /home/siegfried/.clisprc.lisp
[1]> (ql:quickload "cl-markdown")
To load "cl-markdown":
  Load 1 ASDF system:
    cl-markdown
; Loading "cl-markdown"
.
**\* - FUNCALL: undefined function #:BINDING-GENERATOR57557
Rentrées possibles:
USE-VALUE      :R1      Input a value to be used instead of (FDEFINITION '#:BINDING-GENERATOR57557).
RETRY          :R2      Reéssayer
STORE-VALUE    :R3      Input a new value for (FDEFINITION '#:BINDING-GENERATOR57557).
RETRY          :R4      Retry compiling #<CL-SOURCE-FILE "cl-markdown" "dev" "html">.
ACCEPT         :R5      Continue, treating compiling #<CL-SOURCE-FILE "cl-markdown" "dev" "html"> as having been successful.
ABORT          :R6      Give up on "cl-markdown"
ABORT          :R7      Abort main loop
Break 1 MARKDOWN[2]>

**Comment by hraban** [comment]
I assume this was fixed :) closing
