### ISSUE TITLE
System source for dependencies :container-dynamic-classes

### ISSUE THREAD

**Issue by Hellseher** [hraban/cl-markdown#9]
Hi,

I try to build your system for Guix and has an issue to find dependencies listed in asd file

https://github.com/gwkkwg/cl-markdown/blob/master/cl-markdown.asd#L65

Could you, give me a link for source of the project which was mentioned, please?

Thanks

**Comment by ncryptid** [comment]
I'm also having an issue packaging this in guix, though from the looks of it the dependency (cl-containers) has been packaged in guix. Would you care to post your derivation?

**Comment by Hellseher** [comment]
@ncryptid Patch is applied upstream in Guix without cl-containers https://issues.guix.gnu.org/45719

**Comment by hraban** [comment]
Hi all if you have `asdf-system-connections` availabe on your ASDF path you won't need `container-dynamic-classes` anymore. That should fix this issue.

To nyone from Guix: I recently took over maintenance of most of Gary King's packages, including cl-markdown, but I also maintain a Nix package scope for common lisp packages at "https://github.com/hraban/cl-nix-lite". I'm working on making everything build properly, including tests, with clean ASDF definitions. Please feel free to reach out if you want to link up--I can imagine we could help each other :)
